version: '2'
services:
  # Pattern library app server container.
  patternkit:
    container_name: patternkit
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      # Source directory.
      - ./:/var/www/html
      # Used during development, comment out for production.
      #- ./patternkit:/var/www/html/vendor/pattern-builder/pattern-kit
      # XDebug configuration.
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # PHP configuration
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      # SSL Cert for apache.
      - ./docker/cp.crt:/etc/ssl/certs/site.crt
      - ./docker/cp.key:/etc/ssl/certs/site.key
      - ./docker/default-ssl.conf:/etc/apache2/sites-enabled/default-ssl.conf

    environment:
      XDEBUG_CONFIG: remote_host=10.254.254.254
    ports:
      - $PK_LISTEN_PORT:80
      - $PK_HTTPS_LISTEN_PORT:443

# http://localhost:8080/schema/link?data=AAb2CJgO2BDYC2wCmFgC40BtgEtrADWaANGgC4rAAewlkmkAKsABZ7ADOwABB93xz4YxPpVS1KAOlJp2AJyoAzNIzZ0NABwzAA9HuAATfgVQBPYDIDGwAPaJZkSvko5UDNCvgAjYAEJHDXhFAHMqeh1IAH0uKhwVSABfIA==